# -*- coding: utf-8 -*-
"""5_Clasificacion_ataque corazon.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dfjcybTJxdRDvHspjzwv3UaQHRBlNiMg

# Predicción de ataque al corazón (Clasificación)

1. Preparación de Datos
2. División de los datos 70-30
3. Aprendizaje del Modelo
4. Evaluación del Modelo: matriz de confusion, P,R, ROC
5. Guardar el modelo

* El despliegue se realiza en otro jupyter_notebook
"""

#Importamos librerías básicas
import pandas as pd # manipulacion dataframes
import numpy as np  # matrices y vectores
import matplotlib.pyplot as plt #gráfica

"""# 1. Preparación de Datos

"""

#Cargamos los datos
data = pd.read_excel("ataque_corazon.xlsx", sheet_name="Datos")
data.head()

#Corrección tipos de datos
data['hypertension']=data['hypertension'].astype('category')
data['heart_disease']=data['heart_disease'].astype('category')
data['ever_married']=data['ever_married'].astype('category')
data['smoking_status']=data['smoking_status'].astype('category')
data['stroke_ataque_corazon']=data['stroke_ataque_corazon'].astype('category')
data.info()

"""### Data Profiling with `ydata-profiling`

To get a more detailed and interactive overview of the dataset, we'll use the `ydata-profiling` library. This library generates a comprehensive report including statistics, correlations, and visualizations for each column.
"""

# Install ydata-profiling
!pip install ydata-profiling

# Import ProfileReport
from ydata_profiling import ProfileReport

# Generate the profile report
profile = ProfileReport(data, title="Pandas Profiling Report")

# Display the report
profile

"""# 2. División 70-30

"""

#División 70-30
from sklearn.model_selection import train_test_split
X = data.drop("stroke_ataque_corazon", axis = 1) # Variables predictoras
Y = data['stroke_ataque_corazon'] #Variable objetivo
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, stratify=Y) #Muestreo estratificado
Y_train.value_counts().plot(kind='bar')

#Variable objetivo del 30%
#La clase minoritaria tendrá el 50% del tamaño de la clase mayoritaria, adicionando datos sintéticos
from imblearn.over_sampling import SMOTE, SMOTENC

X = data.drop("stroke_ataque_corazon", axis = 1)
Y = data['stroke_ataque_corazon']

smote = SMOTENC(k_neighbors=2, categorical_features=[1,2,3,5], sampling_strategy=0.25)
X_smote, y_smote = smote.fit_resample(X,Y)

# Creamos un dataframe con los resultados (X_smote, y_smote)
data  = pd.DataFrame(columns=X_smote.columns.values, data=X_smote)
data['stroke_ataque_corazon']=y_smote
data['stroke_ataque_corazon'].value_counts().plot(kind='bar')

#Dummies para las variables
# Only apply get_dummies if the column exists
if 'smoking_status' in data.columns:
    data = pd.get_dummies(data, columns=['smoking_status'], drop_first=False, dtype=int)

# Grouped for robustness, ensure all columns exist before processing
columns_to_dummy = ['hypertension','heart_disease','ever_married']
if all(col in data.columns for col in columns_to_dummy):
    data = pd.get_dummies(data, columns=columns_to_dummy, drop_first=True, dtype=int)

data.head()

#LabelEncoder para la variable objetivo
from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()
data["stroke_ataque_corazon"]=labelencoder.fit_transform(data["stroke_ataque_corazon"])
data.head()

Y_test.value_counts().plot(kind='bar', title='Distribución de la Variable Objetivo (30% Test Set)')
plt.xlabel('stroke_ataque_corazon')
plt.ylabel('Cantidad')
plt.show()

"""# 3. Aprendizaje con el 70% y Evaluación con el 30%

# **Tree**
No se normaliza, pierde interpretabilidad
"""

# Before fitting the model, ensure X_train and Y_train are numerical.
# The `data` DataFrame has been processed with get_dummies and LabelEncoder,
# so we need to split it again.
from sklearn.model_selection import train_test_split

X_processed = data.drop("stroke_ataque_corazon", axis=1)
Y_processed = data['stroke_ataque_corazon']

# Re-split the data
# Using a random_state for reproducibility
X_train, X_test, Y_train, Y_test = train_test_split(X_processed, Y_processed, test_size=0.3, stratify=Y_processed, random_state=42)

#Creación del modelo con el conjunto de entrenamiento
from sklearn.tree import DecisionTreeClassifier #DecisionTreeRegressor

modelTree = DecisionTreeClassifier(criterion='gini', min_samples_leaf=50, max_depth=10) #gini, entropy
modelTree.fit(X_train, Y_train) #70% train

from sklearn.tree import plot_tree
plt.figure(figsize=(30,20)) #Tamaño de la imagen
plot_tree(modelTree, feature_names=X_train.columns.values, class_names=labelencoder.classes_, rounded=True,  fontsize=8, filled=True)
plt.show()

#Evaluación 30% (X_test)
from sklearn import metrics

Y_pred = modelTree.predict(X_test) #30% Test
print(Y_pred)

#Exactitud: Correctos/Total
exactitud=metrics.accuracy_score(y_true=Y_test, y_pred=Y_pred)
print(exactitud)

#Matriz de confusion
from sklearn import metrics

cm=metrics.confusion_matrix(y_true=Y_test, y_pred=Y_pred)
cm

#Plot de la matriz de confusion
disp=metrics.ConfusionMatrixDisplay(confusion_matrix=cm,display_labels=labelencoder.classes_)
disp.plot()

#Precision, Recall, f1, exactitud
print(metrics.classification_report( y_true=Y_test, y_pred=Y_pred, target_names=labelencoder.classes_))

metrics.RocCurveDisplay.from_estimator(modelTree,X_test, Y_test)

"""# **KNN**
* Normalización
"""

#Normalizacion las variables numéricas (las dummies no se normalizan)
from sklearn.preprocessing import MinMaxScaler

min_max_scaler = MinMaxScaler()
variables_numericas=['age','avg_glucose_level']


min_max_scaler.fit(data[variables_numericas]) #Ajuste de los parametros sobre 100% de los datos (data): max - min

#Se aplica la normalización a 70%  y 30%
X_train[variables_numericas]= min_max_scaler.transform(X_train[variables_numericas]) #70%
X_test[variables_numericas]= min_max_scaler.transform(X_test[variables_numericas]) #30%
X_train.head()

X_test.head()

#Aprendizaje KNN con 70%
from sklearn.neighbors  import KNeighborsClassifier #KNeighborsRegressor

modelKnn = KNeighborsClassifier(n_neighbors=1, metric='euclidean')#euclidean, minkowski
modelKnn.fit(X_train, Y_train) #70%

#Evaluación de Knn con 30%
from sklearn import metrics

Y_pred = modelKnn.predict(X_test) #30%

#Matriz de confusion
cm=metrics.confusion_matrix(y_true=Y_test, y_pred=Y_pred)
disp=metrics.ConfusionMatrixDisplay(confusion_matrix=cm,display_labels=labelencoder.classes_)
disp.plot()

#Precision, Recall, f1, exactitud
print(metrics.classification_report( y_true=Y_test, y_pred=Y_pred, target_names=labelencoder.classes_))

# Curva ROC
metrics.RocCurveDisplay.from_estimator(modelKnn,X_test, Y_test)

"""# **Red Neuronal**
- Normalizar
"""

#Red Neuronal

from sklearn.neural_network import MLPClassifier #MLPRegressor

#Solo se configura capas ocultas, no se configura capa de entrada y de salida
#activation -> función activación de la oculta: tanh, logistic, linear, relu
#hidden_layer_sizes=5,7 -> dos capas ocultas con 5 neuronas y 7 neuronas
#learning_rate-> tamaño del paso constante o decreciente (constant, adaptive)
#learning_rate_init-> valor tasa de aprendizaje
#momentum-> valor momentum
#max_iter-> iteaciones
#random_state-> semilla para generacion numeros seudoaletorios
modelNN = MLPClassifier(activation="logistic",hidden_layer_sizes=(50), learning_rate='constant',
                     learning_rate_init=0.02, momentum= 0.03, max_iter=500, random_state=3)

modelNN.fit(X_train, Y_train) #70% normalizados

#Loss es la desviación entre Y_train y el Y_pred
loss_values = modelNN.loss_curve_
plt.plot(loss_values)

#Evaluación de Red Neuronal
from sklearn import metrics

Y_pred = modelNN.predict(X_test) #30%

#Matriz de confusion
cm=metrics.confusion_matrix(y_true=Y_test, y_pred=Y_pred)
disp=metrics.ConfusionMatrixDisplay(confusion_matrix=cm,display_labels=labelencoder.classes_)
disp.plot()

#Precision, Recall, f1, exactitud
print(metrics.classification_report( y_true=Y_test, y_pred=Y_pred, target_names=labelencoder.classes_))

# Curva ROC
metrics.RocCurveDisplay.from_estimator(modelNN,X_test, Y_test)

#Imprimir el modelo
print(modelNN.coefs_)  # W
print(modelNN.intercepts_) # b

"""# **SVM**
-Normalizar
"""

#SVM
from sklearn.svm import SVC # SVR
modelSVM = SVC(kernel='rbf',C=1,class_weight="balanced") #'linear', 'poly'->degree=3, 'rbf', 'sigmoid', 'precomputed'
modelSVM.fit(X_train, Y_train) #70%

#Evaluación de SVM
from sklearn import metrics

Y_pred = modelSVM.predict(X_test) #30%

#Matriz de confusion
cm=metrics.confusion_matrix(y_true=Y_test, y_pred=Y_pred)
disp=metrics.ConfusionMatrixDisplay(confusion_matrix=cm,display_labels=labelencoder.classes_)
disp.plot()

#Precision, Recall, f1, exactitud
print(metrics.classification_report( y_true=Y_test, y_pred=Y_pred, target_names=labelencoder.classes_))

# Curva ROC
metrics.RocCurveDisplay.from_estimator(modelSVM,X_test, Y_test)

"""# **Regresión Logística**
-Normalizar

# 5. Guardamos el mejor modelo
Se entrena modelo final con 100% de los datos (X,Y)

Considerando los resultados de los modelos, el KNN parece ser la mejor opción. Su F1-score para la clase 'Sí' (ataque al corazón) es el más alto (0.71) entre todos los modelos evaluados.

Razones para elegir KNN:
El F1-Score para la clase 'Sí' es significativamente mejor que el 0.46 del Árbol de Decisión, el 0.56 de la Red Neuronal y el 0.58 de la SVM. Esto es importante porque en la predicción de ataques al corazón, es prioritario identificar correctamente los casos positivos (minimizar falsos negativos), y el F1-score proporciona un buen equilibrio entre precisión y recall.
"""

# Prepare the final X and Y from the fully processed 'data' DataFrame
X_final = data.drop("stroke_ataque_corazon", axis=1)
Y_final = data['stroke_ataque_corazon']

# Normalize numerical variables in X_final
X_final[variables_numericas]= min_max_scaler.transform(X_final[variables_numericas])

#Entrenamos modelo final
modelNN.fit(X_final, Y_final) #100%

import pickle
filename = 'modelo-class.pkl'
variables= X.columns._values
pickle.dump([modelNN, labelencoder,variables,min_max_scaler], open(filename, 'wb'))
